version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  vercel-orb: i-am-jeetu/vercel-orb@1.0.0

jobs:
  install:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run: npm i vercel
      - vercel-orb/install
      - vercel-orb/deploy:
          vercel-token: S4GKeECRISKzL3zoi6sWOAbp 
          scope-name: simaszurauskas

  # deploy:
  #   docker:
  #     # replace with your preferred image
  #     - image: cimg/base:stable
  #   steps:
  #     - vercel-orb/deploy:
  #         vercel-token: S4GKeECRISKzL3zoi6sWOAbp 
  #         scope-name: simaszurauskas 

workflows:
  main-workfow:
    jobs:
      - install
      # - deploy


